//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresentationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PresentationResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Creation.
        /// </summary>
        internal static string AircraftCreateTitle {
            get {
                return ResourceManager.GetString("AircraftCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Deletion.
        /// </summary>
        internal static string AircraftDeleteTitle {
            get {
                return ResourceManager.GetString("AircraftDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Edition.
        /// </summary>
        internal static string AircraftEditTitle {
            get {
                return ResourceManager.GetString("AircraftEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircrafts.
        /// </summary>
        internal static string AircraftIndexTitle {
            get {
                return ResourceManager.GetString("AircraftIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport Creation.
        /// </summary>
        internal static string AirportCreateTitle {
            get {
                return ResourceManager.GetString("AirportCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport Deletion.
        /// </summary>
        internal static string AirportDeleteTitle {
            get {
                return ResourceManager.GetString("AirportDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport Edition.
        /// </summary>
        internal static string AirportEditTitle {
            get {
                return ResourceManager.GetString("AirportEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        internal static string AirportIndexTitle {
            get {
                return ResourceManager.GetString("AirportIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Creation.
        /// </summary>
        internal static string FlightCreateTitle {
            get {
                return ResourceManager.GetString("FlightCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        internal static string FlightIndexTitle {
            get {
                return ResourceManager.GetString("FlightIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA code.
        /// </summary>
        internal static string IATA {
            get {
                return ResourceManager.GetString("IATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IATA code should a maximun length of 3 characters. P.e.: ABC.
        /// </summary>
        internal static string IATAMaxLength {
            get {
                return ResourceManager.GetString("IATAMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IATA code is required.
        /// </summary>
        internal static string IATARequired {
            get {
                return ResourceManager.GetString("IATARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude is required.
        /// </summary>
        internal static string LatitudeRequired {
            get {
                return ResourceManager.GetString("LatitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude is required.
        /// </summary>
        internal static string LongitudeRequired {
            get {
                return ResourceManager.GetString("LongitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is required.
        /// </summary>
        internal static string ModelRequired {
            get {
                return ResourceManager.GetString("ModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff Effort.
        /// </summary>
        internal static string TakeoffEffort {
            get {
                return ResourceManager.GetString("TakeoffEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The takeoff effort is required.
        /// </summary>
        internal static string TakeOffEffortRequired {
            get {
                return ResourceManager.GetString("TakeOffEffortRequired", resourceCulture);
            }
        }
    }
}
